import { existsSync, readFileSync } from "node:fs";
import { join as pathJoin, relative as pathRelative } from "node:path";
import { getModuleDir, saveFileSync, walkDirSync } from "../lib/fs.js";

let indexes = {};
const elementRegExp = /<([a-z][a-z0-9]*)[^>]*>/g;
const attrsRegExp =
	/(class|is|type|role|aria-[\w-]+)=["']?((?:.(?!["']?\s+(?:\S+)=|\s*\/?[>"']))+.)["']?/g;

// "build:styles": "npm run build:styles:ds && npm run build:styles:postcss",
// 		"build:styles:ds": "npx ds extract build --css-path src/styles/app.css --theme ./theme.css --debug",
// 		"build:styles:postcss": "postcss src/styles/*.css -d static/css/ --no-map",
// 		"build:styles:copy": "cp static/css/* build/css/",
// 		"build:styles:inline": "npx ds inline build/css/app.css build --debug",

// TODO when other attr are present, fails to parse ...
const _htmlRegExp =
	/(?:(?=(\s+(?:type="?([^"]*)"?|class="?([^"]*)"?|is="?([^"]*)"?)|[^\s>]+|\s+))\1)*/;
const _elemSplitRegExp = /[/> ]/;
const parse = (content) => {
	let matchElement = elementRegExp.exec(content);
	while (matchElement) {
		const [elem, tag] = matchElement;

		indexes.tags[tag] ??= 0;
		indexes.tags[tag] += 1;
		const matchAttrs = elem.match(attrsRegExp);
		if (!matchAttrs) {
			matchElement = elementRegExp.exec(content);
			continue;
		}
		const attrs = {};
		for (const attr of matchAttrs) {
			const eq = attr.indexOf("=");
			const key = attr.substring(0, eq);
			const value =
				attr.charAt(eq + 1) === '"'
					? attr.substring(eq + 2, attr.length - 1)
					: attr.substring(eq + 1);
			attrs[key] = value;
		}

		if (tag === "input" && attrs.type) {
			const tagExpression = `${tag}[type=${attrs.type}]`;
			indexes.tags[tagExpression] ??= 0;
			indexes.tags[tagExpression] += 1;
		}

		if (attrs.class) {
			for (const className of attrs.class.split(" ")) {
				let key = `.${className}`;
				indexes.classes[key] ??= 0;
				indexes.classes[key] += 1;
				key = `${tag}.${className}`;
				indexes.classes[key] ??= 0;
				indexes.classes[key] += 1;
			}
		}

		if (attrs.role) {
			const key = `${tag}[role=${attrs.role}]`;
			indexes.roles[key] ??= 0;
			indexes.roles[key] += 1;
		}

		for (const [key, value] of Object.entries(attrs)) {
			if (key.startsWith("aria-") && value) {
				const prefix = value.split("-")[0];
				if (prefix) {
					const ariaKey = `${tag}[${key}^=${prefix}-]`;
					indexes.arias[ariaKey] ??= 0;
					indexes.arias[ariaKey] += 1;
				}
			}
		}

		if (attrs.is) {
			indexes.pewc[attrs.is] ??= 0;
			indexes.pewc[attrs.is] += 1;
		}
		matchElement = elementRegExp.exec(content);
	}
};

// Svelte 5 SSR outputs JS objects like { class: "container-slices", is: "ds-card" }
const jsAttrRegExp = /(?:class|is|type|role|aria-[\w-]+)\s*:\s*"([^"]*)"/g;
const jsAttrKeyRegExp = /(class|is|type|role|aria-[\w-]+)\s*:\s*"([^"]*)"/;
const parseJS = (content) => {
	let match = jsAttrRegExp.exec(content);
	while (match) {
		const keyMatch = match[0].match(jsAttrKeyRegExp);
		if (keyMatch) {
			const [, key, value] = keyMatch;
			if (key === "class") {
				for (const className of value.split(" ")) {
					const k = `.${className}`;
					indexes.classes[k] ??= 0;
					indexes.classes[k] += 1;
				}
			} else if (key === "is") {
				indexes.pewc[value] ??= 0;
				indexes.pewc[value] += 1;
			} else if (key === "role") {
				indexes.roles[`[role=${value}]`] ??= 0;
				indexes.roles[`[role=${value}]`] += 1;
			} else if (key.startsWith("aria-") && value) {
				const prefix = value.split("-")[0];
				if (prefix) {
					const ariaKey = `[${key}^=${prefix}-]`;
					indexes.arias[ariaKey] ??= 0;
					indexes.arias[ariaKey] += 1;
				}
			}
		}
		match = jsAttrRegExp.exec(content);
	}
};

const aboveTheFold = new Set([
	"layers/base.css",
	"layers/media.css",
	"elements/nav.css",
	"elements/a.css",
	"elements/button.css",
	"elements/hgroup.css",
	"elements/h1.css",
	"elements/li.css",
	"elements/search.css",
	"elements/ul.css",
	"classes/.container.css",
	"classes/.container-aside.css",
	"classes/.container-slices.css",
	"classes/.container-toc.css",
	"classes/.form-errors.css",
	"classes/.visually-hidden.css",
	"classes/a.back.css",
	"classes/a.button.css",
	"classes/a.skip.css",
	"classes/details.chevron.css",
	"theme.css",
	"theme-custom",
]);

const buildCSS = (
	{ namespace = "willfarrell-ds", tags, classes, roles, arias, pewc } = {},
	theme,
) => {
	const vanillaPath = getModuleDir(`@${namespace}/vanilla`);
	const header = `/* generated by @${namespace}/cli */\n`;
	const imports = [];

	imports.push({
		key: "layers/base.css",
		line: `@import "@${namespace}/vanilla/layers/base.css";\n`,
	});
	imports.push({
		key: "layers/media.css",
		line: `@import "@${namespace}/vanilla/layers/media.css";\n`,
	});

	let list = Object.keys(tags);
	list.sort();
	for (const key of list) {
		if (existsSync(`${vanillaPath}/elements/${key}.css`)) {
			imports.push({
				key: `elements/${key}.css`,
				line: `@import "@${namespace}/vanilla/elements/${key}.css";\n`,
			});
		}
	}
	list = Object.keys(classes);
	list.sort();
	const addedClasses = new Set();
	for (const key of list) {
		if (existsSync(`${vanillaPath}/classes/${key}.css`)) {
			if (!addedClasses.has(`classes/${key}.css`)) {
				addedClasses.add(`classes/${key}.css`);
				imports.push({
					key: `classes/${key}.css`,
					line: `@import "@${namespace}/vanilla/classes/${key}.css";\n`,
				});
			}
		}
		// For dotted class keys (.className), also check tag-qualified files (tag.className.css)
		if (key.startsWith(".")) {
			const className = key.substring(1);
			for (const tag of Object.keys(tags)) {
				const tagKey = `${tag}.${className}`;
				const cssKey = `classes/${tagKey}.css`;
				if (
					!addedClasses.has(cssKey) &&
					existsSync(`${vanillaPath}/classes/${tagKey}.css`)
				) {
					addedClasses.add(cssKey);
					imports.push({
						key: cssKey,
						line: `@import "@${namespace}/vanilla/classes/${tagKey}.css";\n`,
					});
				}
			}
		}
	}
	list = Object.keys(roles);
	list.sort();
	for (const key of list) {
		if (existsSync(`${vanillaPath}/classes/${key}.css`)) {
			imports.push({
				key: `classes/${key}.css`,
				line: `@import "@${namespace}/vanilla/classes/${key}.css";\n`,
			});
		}
	}
	list = Object.keys(arias);
	list.sort();
	for (const key of list) {
		if (existsSync(`${vanillaPath}/classes/${key}.css`)) {
			imports.push({
				key: `classes/${key}.css`,
				line: `@import "@${namespace}/vanilla/classes/${key}.css";\n`,
			});
		}
	}
	list = Object.keys(pewc);
	list.sort();
	for (const key of list) {
		if (existsSync(`${vanillaPath}/components/${key}.css`)) {
			imports.push({
				key: `components/${key}.css`,
				line: `@import "@${namespace}/vanilla/components/${key}.css";\n`,
			});
		}
	}

	imports.push({
		key: "theme.css",
		line: `@import "@${namespace}/vanilla/theme.css";\n`,
	});
	imports.push({
		key: "theme-custom",
		line: `@import "${theme}";\n`,
	});

	return { imports, header };
};

const splitCSS = (imports, header) => {
	const above = [];
	const below = [];
	for (const { key, line } of imports) {
		if (aboveTheFold.has(key)) {
			above.push(line);
		} else {
			below.push(line);
		}
	}
	return {
		app: header + imports.map((i) => i.line).join(""),
		above: header + above.join(""),
		below: below.join(""),
	};
};

// const buildJS = ({ pewc } = {}) => {
//   const list = Object.keys(options.pewc.bootstrap)
//   list.sort()
//   let bootstrap = `/* generated by @design-system/cli */\n`
//   for (const key of list) {
//     if (existsSync(`${corePath}/${key}.js`)) {
//       bootstrap += `import '@design-system/core/${key}.js'\n`
//     }
//   }
//   return bootstrap
// }

// const copyPEWC = ({ pewc }) => {
//
// }

const extract = (options = {}) => {
	const inputDirs = Array.isArray(options.inputDir)
		? options.inputDir
		: [options.inputDir];
	indexes = { tags: {}, classes: {}, roles: {}, arias: {}, pewc: {} };

	for (const input of inputDirs) {
		const sourceDir = pathJoin(process.cwd(), input);
		for (const filePath of walkDirSync(sourceDir, ".html")) {
			if (options.debug) {
				console.log("Parse", filePath);
			}
			const content = readFileSync(filePath).toString();
			parse(content);
		}
		for (const filePath of walkDirSync(sourceDir, ".js")) {
			if (options.debug) {
				console.log("Parse", filePath);
			}
			const content = readFileSync(filePath).toString();
			parse(content);
			parseJS(content);
		}
	}

	if (options.debug) {
		console.log("tags", Object.keys(indexes.tags).sort());
		console.log("classes", Object.keys(indexes.classes).sort());
		console.log("roles", Object.keys(indexes.roles).sort());
		console.log("arias", Object.keys(indexes.arias).sort());
		console.log("pewc", Object.keys(indexes.pewc).sort());
	}

	if (options.outputDir) {
		const relativeTheme = `./${pathRelative(options.outputDir, options.theme)}`;
		const { imports, header } = buildCSS(indexes, relativeTheme);
		const { app, above, below } = splitCSS(imports, header);
		saveFileSync(pathJoin(options.outputDir, "app.css"), app);
		saveFileSync(pathJoin(options.outputDir, "above.css"), above);
		saveFileSync(pathJoin(options.outputDir, "below.css"), below);
		if (options.debug) {
			console.log("Saved", options.outputDir);
		}
	}
	if (options.debug) {
		console.log("Done!");
	}
};

export default extract;
