import { redirect } from '@sveltejs/kit';
import { building } from '$app/environment';

import preferredLanguages from 'negotiator/lib/language.js';

// import * as minifyHtml from "@minify-html/js" // Faster, but: Note that you need plugins to import files that are not JavaScript
import { minify as htmlMinify } from 'html-minifier-terser'; // TODO switch for esbuild
import { version as codeVersion } from '../../package.json' assert { type: 'json' };

let version = codeVersion;
if (process.env.NODE_ENV !== 'production') {
	version += '-' + Date.now();
}

const htmlMinifyOptions = {
	caseSensitive: true,
	collapseBooleanAttributes: true,
	collapseInlineTagWhitespace: true,
	collapseWhitespace: true,
	conservativeCollapse: true,
	continueOnParseError: true,
	html5: true,
	includeAutoGeneratedTags: true,
	keepClosingSlash: false,
	minifyCSS: false,
	minifyJS: false,
	minifyURLs: false,
	preserveLineBreaks: false,
	quoteCharacter: '"',
	removeAttributeQuotes: true,
	removeComments: true,
	removeEmptyAttributes: true,
	removeEmptyElements: false, // Needed for icons and background images
	removeOptionalTags: false, //
	removeRedundantAttributes: true,
	removeScriptTypeAttributes: true,
	removeStyleLinkTypeAttributes: true,
	removeTagWhitespace: false,
	sortAttributes: true,
	sortClassName: true,
	trimCustomFragments: true,
	useShortDoctype: true
};

const localeHandler = async ({ event, resolve }) => {
	const lang = 'en-ca';
	// inject locale into <html>
	const response = await resolve(event, {
		transformPageChunk: ({ html }) => {
			// html = html.replace(
			//   '<html>',
			//   `<html lang="${lang}" dir="ltr">`
			// )
			html = html.replace(/\?v="/g, `?v=${version}"`); // TODO make more performant - https://adamtuttle.codes/blog/2021/sveltekit-customizing-app-html-at-runtime/
			html = htmlMinify(html, htmlMinifyOptions);
			return html;
		}
	});
	response.headers.set('Content-Language', lang);
	return response;
};

export default localeHandler;
