// import * as minifyHtml from "@minify-html/js" // Faster, but: Note that you need plugins to import files that are not JavaScript
import { minify as htmlMinify } from "html-minifier-terser"; // TODO switch for esbuild

const htmlMinifyOptions = {
	caseSensitive: true,
	collapseBooleanAttributes: true,
	collapseInlineTagWhitespace: true,
	collapseWhitespace: true,
	conservativeCollapse: true,
	continueOnParseError: true,
	html5: true,
	includeAutoGeneratedTags: true,
	keepClosingSlash: false,
	minifyCSS: false,
	minifyJS: false,
	minifyURLs: false,
	preserveLineBreaks: false,
	quoteCharacter: '"',
	removeAttributeQuotes: true,
	removeComments: true,
	removeEmptyAttributes: true,
	removeEmptyElements: false, // Needed for icons and background images
	removeOptionalTags: false, //
	removeRedundantAttributes: true,
	removeScriptTypeAttributes: true,
	removeStyleLinkTypeAttributes: true,
	removeTagWhitespace: false,
	sortAttributes: true,
	sortClassName: true,
	trimCustomFragments: true,
	useShortDoctype: true,
};

const minifyHtmlMiddleware = async ({ event, resolve }) => {
	const response = await resolve(event, {
		transformPageChunk: ({ html }) => {
			html = htmlMinify(html, htmlMinifyOptions);
			return html;
		},
	});
	return response;
};

export default minifyHtmlMiddleware;
